(ns replete.io-impl)

;js/REPLETE_COPY
;js/REPLETE_DELETE
;js/REPLETE_FILE_INPUT_STREAM_CLOSE
;js/REPLETE_FILE_INPUT_STREAM_OPEN
;js/REPLETE_FILE_INPUT_STREAM_READ
;js/REPLETE_FILE_OUTPUT_STREAM_CLOSE
;js/REPLETE_FILE_OUTPUT_STREAM_FLUSH
;js/REPLETE_FILE_OUTPUT_STREAM_OPEN
;js/REPLETE_FILE_OUTPUT_STREAM_WRITE
;js/REPLETE_FILE_READER_CLOSE
;js/REPLETE_FILE_READER_OPEN
;js/REPLETE_FILE_READER_READ
;js/REPLETE_FILE_WRITER_CLOSE
;js/REPLETE_FILE_WRITER_FLUSH
;js/REPLETE_FILE_WRITER_OPEN
;js/REPLETE_FILE_WRITER_WRITE
;js/REPLETE_FSTAT
;js/REPLETE_IS_DIRECTORY
;js/REPLETE_LIST_FILES
;js/REPLETE_LOAD
;js/REPLETE_LOAD_FROM_JAR
;js/REPLETE_MKDIRS
;js/REPLETE_RAW_FLUSH_STDERR
;js/REPLETE_RAW_FLUSH_STDOUT
;js/REPLETE_RAW_READ_STDIN
;js/REPLETE_REQUEST
;js/REPLETE_SLEEP

;; Add each of the above to a global variable so that it is accessed in the code


(defn- replete-load
  [url]
  )
