version: 0.2

env:
  variables:
    CLJ_VERSION: "1.10.0.442"

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - curl -O https://download.clojure.org/install/linux-install-${CLJ_VERSION}.sh
      - chmod +x linux-install-${CLJ_VERSION}.sh
      - ./linux-install-${CLJ_VERSION}.sh

  build:
    commands:
      - clojure -A:dist-worker
      - clojure -A:dist-app

cache:
  paths:
    - '/root/.m2/**/*'