version: 0.2

env:
  variables:
    CLJ_VERSION: "1.10.0.442"

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - curl -O https://download.clojure.org/install/linux-install-${CLJ_VERSION}.sh
      - chmod +x linux-install-${CLJ_VERSION}.sh
      - ./linux-install-${CLJ_VERSION}.sh

  build:
    commands:
      - ls -l
      - rm -rf ~/.gitlibs
      - rm -rf resources/public/js/compiled cljs-test-runner-out .cpcache
      - clojure -A:dist
      - clojure -A:test | tee test.out
      - grep '0 failures, 0 errors.' test.out
  post_build:
    finally:
      - scripts/invalidate-cdn.sh

cache:
  paths:
    - '/root/.m2/**/*'
